k8s-infra:
  presets:
    logsCollection:
      blacklist:
        namespaces:
          - default
          - kube-node-lease
          - kube-public
          - kube-system
          - local-path-storage
          - platform
          # we only want this
          #- the-app
